Models/ViewModel/Home/ImgAppuntamentiDellaSettimanaDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace SSResurrezioneBR.Models.ViewModel.Home
{
    public class ImgAppuntamentiDellaSettimanaDetailViewModel
    {
        public int? ImageId {get; set;}
        public string? ImagePath {get; set;}
        

        public static ImgAppuntamentiDellaSettimanaDetailViewModel FromDataRow (DataRow imgAppuntamentiDellaSettimanaDetailRow)
        {
            ImgAppuntamentiDellaSettimanaDetailViewModel imgForCarouselDetailViewModel = new ImgAppuntamentiDellaSettimanaDetailViewModel {
                ImageId = Convert.ToInt32(imgAppuntamentiDellaSettimanaDetailRow["IdFoto"]),
                ImagePath = string.Concat("/", imgAppuntamentiDellaSettimanaDetailRow["PathFoto"])
            };
            return imgForCarouselDetailViewModel;
        }
    }    
}

Models/ViewModel/Home/ImgAppuntamentiDellaSettimanaEditInputModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using SSResurrezioneBR.Controllers;

namespace SSResurrezioneBR.Models.ViewModel.Home
{
    public class ImgAppuntamentiDellaSettimanaEditInputModel
    {
        [Required]
        public int? IdFoto {get; set;}
        [Display(Name = "Immagine rappresentativa")]
        public string? PathFoto {get; set;}
        public string? ReviewerFoto { get; set; }

        public static ImgAppuntamentiDellaSettimanaEditInputModel FromDataRow(DataRow imgAppuntamentiDellaSettimanaRow)
        {
            ImgAppuntamentiDellaSettimanaEditInputModel imgAppuntamentiDellaSettimanaEditInputModel = new ImgAppuntamentiDellaSettimanaEditInputModel {
                IdFoto = Convert.ToInt32(imgAppuntamentiDellaSettimanaRow["IdFoto"]),
                PathFoto = (string) imgAppuntamentiDellaSettimanaRow["PathFoto"],
                ReviewerFoto = (imgAppuntamentiDellaSettimanaRow["reviewerFoto"] ?? String.Empty).ToString(),
                RowVersion = (string) imgAppuntamentiDellaSettimanaRow["RowVersion"]
            };
            return imgAppuntamentiDellaSettimanaEditInputModel;
        }
        [Display(Name = "Nuova Immagine...")]
        public IFormFile? Image {get; set;}
        public string RowVersion { get; set; }
    }
}

Models/ViewModel/Home/ImgAppuntamentiDellaSettimanaViewModel.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace SSResurrezioneBR.Models.ViewModel.Home
{
    public class ImgAppuntamentiDellaSettimanaViewModel
    {
        public int? IdFoto {get; set;}
        public string? PathFoto {get; set;}
        public string? ReviewerFoto {get; set;}

        public static ImgAppuntamentiDellaSettimanaViewModel FromDataRow(DataRow imgAppuntamentiDellaSettimanaRow)
        {
            ImgAppuntamentiDellaSettimanaViewModel imgAppuntamentiDellaSettimanaViewModel = new ImgAppuntamentiDellaSettimanaViewModel {
                IdFoto = Convert.ToInt32(imgAppuntamentiDellaSettimanaRow["IdFoto"]),
                PathFoto = (string)imgAppuntamentiDellaSettimanaRow["PathFoto"],
                ReviewerFoto = (imgAppuntamentiDellaSettimanaRow["ReviewerFoto"] ?? String.Empty).ToString()
            };
            return imgAppuntamentiDellaSettimanaViewModel;
        }
    }
}

Models/ViewModel/Home/ImgForCarouselDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace SSResurrezioneBR.Models.ViewModel.Home
{
    public class ImgForCarouselDetailViewModel
    {
        public int? ImageId {get; set;}
        public string? ImagePath {get; set;}
        public string? ImageContentTitle {get; set;}
        public int? ImageVisible {get; set;}
        public string? ImageContentDescription {get; set;}
        public string? ImageEventCreator {get; set;}
        public string? ImageLabel {get;set;}

        public static ImgForCarouselDetailViewModel FromDataRow (DataRow imgForCarouselDetailRow)
        {
            ImgForCarouselDetailViewModel imgForCarouselDetailViewModel = new ImgForCarouselDetailViewModel {
                ImageId = Convert.ToInt32(imgForCarouselDetailRow["Image_Id"]),
                ImagePath = string.Concat("/",imgForCarouselDetailRow["Image_Path"]),
                ImageContentTitle = (string) imgForCarouselDetailRow["Image_Content_Title"],
                ImageVisible = Convert.ToInt32(imgForCarouselDetailRow["Image_Visible"]),
                ImageContentDescription = (string) imgForCarouselDetailRow["Image_Content_Description"],
                ImageEventCreator = (imgForCarouselDetailRow["Image_Event_Creator"] ?? String.Empty).ToString(),
                ImageLabel = (string) imgForCarouselDetailRow["Image_Label"]
            };
            return imgForCarouselDetailViewModel;
        }
    }    
}

Models/ViewModel/Home/ImgForCarouselViewModel.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace SSResurrezioneBR.Models.ViewModel.Home
{
    public class ImgForCarouselViewModel
    {
        public int? ImageId {get; set;}
        public string? ImagePath {get; set;}
        public string? ImageLabel {get; set;}
        public string? ImageContentTitle {get; set;}
        public int? ImageVisible {get; set;}
        public string? ImageEventCreator {get; set;}

        public static ImgForCarouselViewModel FromDataRow(DataRow imgForCarouselRow)
        {
            ImgForCarouselViewModel imgForCarouselViewModel = new ImgForCarouselViewModel {
                ImageId = Convert.ToInt32(imgForCarouselRow["Image_Id"]),
                ImagePath = (string)imgForCarouselRow["Image_Path"],
                ImageLabel = (string) imgForCarouselRow["Image_Label"],
                ImageContentTitle = (string) imgForCarouselRow["Image_Content_Title"],
                ImageVisible = Convert.ToInt16(imgForCarouselRow["Image_Visible"]),
                ImageEventCreator = (imgForCarouselRow["Image_Event_Creator"] ?? String.Empty).ToString()
            };
            return imgForCarouselViewModel;
        }
    }
}

Models/ViewModel/Home/SantiDelGiornoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SSResurrezioneBR.Models.ViewModel.Home
{
    public partial class SantiDelGiornoViewModel
    {
        public string? Nome {get;set;}
        public string? Tipologia {get;set;}
        public string? Data {get;set;}
        public string? @Default {get;set;}
        public string? Permalink {get;set;}
        public string? UrlImmagine {get;set;}
        public string? Descrizione {get;set;}
    } 
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using SSResurrezioneBR.Models;
using SSResurrezioneBR.Models.Entities;
using SSResurrezioneBR.Models.Exceptions;
using SSResurrezioneBR.Models.Exceptions.Application;
using SSResurrezioneBR.Models.InputModels;
using SSResurrezioneBR.Models.Services.Application.AppuntamentiDellaSettimana;
using SSResurrezioneBR.Models.Services.Application.CallApiSantiDelGiorno;
using SSResurrezioneBR.Models.Services.Application.ImgForCarousel;
using SSResurrezioneBR.Models.ViewModel.CoroPolifonicoMaterMisericordie;
using SSResurrezioneBR.Models.ViewModel.Home;
using System.Diagnostics;
using System.Dynamic;
using System.Reflection;

namespace SSResurrezioneBR.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IImgForCarouselService _imgForCarouselService;
    private readonly IConfiguration _configuration;
    private readonly ICallApiSantiDelGiornoService _callApiSantiDelGiornoService;
    private readonly IImgAppuntamentiDellaSettimanaService _imgAppuntamentiDellaSettimanaService;

    public HomeController(IConfiguration configuration, 
            ILogger<HomeController> logger, 
            IImgForCarouselService imgForCarouselService, 
            ICallApiSantiDelGiornoService callApiSantiDelGiornoService,
            IImgAppuntamentiDellaSettimanaService imgAppuntamentiDellaSettimana)
    {
        _configuration = configuration;
        _imgForCarouselService = imgForCarouselService;
        _callApiSantiDelGiornoService = callApiSantiDelGiornoService;
        _imgAppuntamentiDellaSettimanaService = imgAppuntamentiDellaSettimana;
        _logger = logger;
    }

    public async Task<IActionResult> Index()
    {
        ViewData["Title"] = "Pagina Principale";
        dynamic myModel = new ExpandoObject();
        try
        {
            var listImgForCarouselViewModel = new List<ImgForCarouselViewModel>();
            listImgForCarouselViewModel = await _imgForCarouselService.GetImgForCarouselAsync();
            var imgAppuntamentiDellaSettimanaViewModel = new ImgAppuntamentiDellaSettimanaViewModel();
            imgAppuntamentiDellaSettimanaViewModel = await _imgAppuntamentiDellaSettimanaService.GetImgAppuntamentiDellaSettimanaAsync();

            // santi del giorno
            myModel.santiDelGiorno = await _callApiSantiDelGiornoService.GetSantiDelGiornoAsync();
            
            // immagini Attivitá in corso
            myModel.imgForCarousel = listImgForCarouselViewModel;

            // immagine Appuntamenti della settimana
            myModel.appuntamentiDellaSettimana = imgAppuntamentiDellaSettimanaViewModel;
        }
        catch (HttpRequestException ex)
        {
            // Handle any exceptions that occurred during the request
            _logger.LogInformation("Si è verificato il seguente errore: {0} ", ex.Message);
        }

        return View(myModel);
    }

    public ActionResult ModalPopUp()  
    {  
        return View();  
    }  

    // creazione di una iniziativa visibile nella home
    public IActionResult CreateInitiative(){
        ViewData["Title"] = "Crea una nuova iniziativa";
        var inputModel = new CreateInitiativeInputModel();
        return View(inputModel);
    }

    [HttpPost]
    public async Task<IActionResult> CreateInitiative(CreateInitiativeInputModel inputModel){
        if (ModelState.IsValid){
            try{
                ImgForCarouselDetailViewModel imageForCarousel = await _imgForCarouselService.CreateInitiativeAsync(inputModel);
                return RedirectToAction(nameof(EditInitiative), new { id = imageForCarousel.ImageId });
                //return RedirectToAction(nameof(Index));
                //return RedirectToAction(nameof(Index), nameof(EditInitiative), inputModel);
            }
            catch (TitleUnavailableException){
                ModelState.AddModelError(nameof(inputModel.Image_Content_Title), "Questo titolo giá esiste");
            }
        }
            
        ViewData["Title"] = "Crea una nuova iniziativa";
        return View(inputModel);
    }
    
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    public async Task<IActionResult> CreateInitiativeIsTitleAvailable(CreateInitiativeInputModel inputModel){
        bool result = await _imgForCarouselService.CreateInitiativeIsTitleAvailableAsync(inputModel.Image_Content_Title);
        return Json(result);
    }

    public async Task<IActionResult> IsTitleAvailable(ImgForCarouselEditInputModel inputModel){
        bool result = await _imgForCarouselService.IsTitleAvailableAsync(inputModel.ImageContentTitle, (long)inputModel.ImageId);
        return Json(result);
    }

    public async Task<IActionResult> EditInitiative(long id)
    {
        ImgForCarouselEditInputModel inputModel = await _imgForCarouselService.GetImgForCarouselForEditingAsync(id);

        // il titolo della pagina cambia se trattasi di nuovo inserimento o di modifica
        if (string.IsNullOrEmpty(inputModel.ImageLabel) && string.IsNullOrEmpty(inputModel.ImageContentDescription))
        {
            ViewData["Title"] = "Crea una nuova iniziativa";
        }
        else
        {
            ViewData["Title"] = "Modifica Iniziativa";
        }
        return View(inputModel);
    }
    [HttpPost]
    public async Task<IActionResult> EditInitiative(ImgForCarouselEditInputModel inputModel)
    {
        var imagePath = inputModel.ImagePath;
        if (imagePath == null)
        {
            inputModel.ImagePath = @"img/IniziativeInCorso/defaultImage.jpg";
        }
        if (ModelState.IsValid){
            try{
                ImgForCarouselDetailViewModel imgForCarousel = await _imgForCarouselService.EditImgForCarouselAsync(inputModel);
                TempData["MessaggioDiConferma"]="I dati sono stati salvati con successo";
                return RedirectToAction(nameof(Index),nameof(ImgForCarousel), new{id = inputModel.ImageId});
            }
            catch(TitleUnavailableException){
                ModelState.AddModelError(nameof(ImgForCarouselEditInputModel.ImageContentTitle),"Questo titolo giá esiste");
            }
            catch (ImgInvalidException)
            {
                ModelState.AddModelError(nameof(ImgForCarouselEditInputModel.Image), "L\'immagine selezionata non é valida");
            }
            catch (OptimisticConcurrencyException)
            {
                ModelState.AddModelError("", $"Spiacente, il salvataggio non é andato a buon fine perché nel frattempo un altro utente ha aggiornato \"Iniziative in corso\". Ti invito ad aggiornare la pagina e ripetere le modifiche.");
            }
            catch (Exception ex) {
                ModelState.AddModelError(nameof(ImgForCarouselEditInputModel.ImagePath), ex.Message);
            }
        }
        // il titolo della pagina cambia se trattasi di nuovo inserimento o di modifica
        if (string.IsNullOrEmpty(inputModel.ImageLabel) || string.IsNullOrEmpty(inputModel.ImageContentDescription))
        {
            ViewData["Title"] = "Crea una nuova iniziativa";
        }
        else
        {
            ViewData["Title"] = "Modifica Iniziativa";
        }
        return View(inputModel);
    }
    
    public async Task<IActionResult> DeleteInitiative(long id)
    {
        if (ModelState.IsValid)
        {
            try
            {
                await _imgForCarouselService.DeleteInitiativeAsync(id);
                TempData["MessaggioDiConferma"] = "L\'iniziativa è stata eliminata con successo";
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(nameof (DeleteInitiative), "Hoops! qualcosa è andato storto, l\'iniziativa non è stata eliminata!");
            }
        }
        return RedirectToAction("Index", "Home");
    }

    public async Task<IActionResult> EditAppuntamentiDellaSettimana(long id)
    {
        ViewData["Title"] = "Modifica Appuntamenti della Settimana";
        ImgAppuntamentiDellaSettimanaEditInputModel inputModel = await _imgAppuntamentiDellaSettimanaService.GetImgAppuntamentiDellaSettimanaForEditingAsync(id);
        return View(inputModel);
    }
    [HttpPost]
    public async Task<IActionResult> EditAppuntamentiDellaSettimana(ImgAppuntamentiDellaSettimanaEditInputModel inputModel)
    {
        if (ModelState.IsValid)
        {
            try
            {
                ImgAppuntamentiDellaSettimanaDetailViewModel imgAppuntamentiDellaSettimana = await _imgAppuntamentiDellaSettimanaService.EditImgAppuntamentiDellaSettimanaAsync(inputModel);
                TempData["MessaggioDiConferma"] = $"L'immagine \"Appuntamenti della settimana\" é stata salvata con successo";
                string homeControllerName = nameof(HomeController);
                return RedirectToAction(nameof(Index), homeControllerName.Replace("Controller", ""));
                //return RedirectToAction(nameof(EditAppuntamentiDellaSettimana), new { id = inputModel.IdFoto });
            }
            catch (ImgInvalidException)
            {
                ModelState.AddModelError(nameof(ImgAppuntamentiDellaSettimanaEditInputModel.Image), "L\'immagine selezionata non é valida");
            }
            catch (OptimisticConcurrencyException)
            {
                ModelState.AddModelError("", $"Spiacente, il salvataggio non é andato a buon fine perché nel frattempo un altro utente ha aggiornato \"Appuntamenti della Settimana\". Ti invito ad aggiornare la pagina e ripetere le modifiche.");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(nameof(ImgAppuntamentiDellaSettimanaEditInputModel.Image), ex.Message);
            }

Controllers/ImgForCarouselController.cs
using Microsoft.AspNetCore.Mvc;
using SSResurrezioneBR.Models.Services.Application.ImgForCarousel;
using SSResurrezioneBR.Models.ViewModel.Home;
 
namespace SSResurrezioneBR.Controllers
{
    public class ImgForCarouselController : Controller
    {
        private readonly IImgForCarouselService _imgForCarousel;

        public ImgForCarouselController(IImgForCarouselService imgForCarousel)
        {
            this._imgForCarousel = imgForCarousel;
        }
        // Controller di pagina di dettaglio delle attivitá
        public async Task<IActionResult> Index(long id)
        {           
            ImgForCarouselDetailViewModel imgForCarouselDetailViewModel = new ();
            imgForCarouselDetailViewModel = await _imgForCarousel.GetImgForCarouselDetailAsync(id);
            ViewData["Title"] = imgForCarouselDetailViewModel.ImageLabel;
            return View(imgForCarouselDetailViewModel);
        }
    }
}

Views/Home/CreateInitiative.cshtml
@model CreateInitiativeInputModel

<h2>@ViewData["Title"]</h2>

<form method="post">
    <div class="row">
        <div class="col-12">
            <div asp-validation-summary="All"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <input type="text" asp-for="Image_Content_Title" class="form-control form-control-lg" placeholder="Inserisci il titolo dell'iniziativa">
            <span asp-validation-for="Image_Content_Title"></span>
        </div>
        <div class="col-md-4">
            <button type="submit" class="btn btn-primary btn-lg btn-block"><i class="fas fa-rocket"></i> Crea</button>
        </div>
    </div>
</form>
@section Scripts{
    <partial name="_Validation"></partial>
}

Views/Home/EditInitiative.cshtml
@model ImgForCarouselEditInputModel
<section class="imgForCarousel-info">
    <form method="post" asp-controller="Home" asp-action="EditInitiative" enctype="multipart/form-data">
        <input type="hidden" asp-for="RowVersion" />
        <div class="row p-2">
            <div class="col-md-10">
                <h1>@ViewData["Title"]</h1>
            </div>
            <div class="col-md-1 d-flex justify-content-center">
                <button type="submit" class="btn btn-primary btn-lg btn-block"><i class="fa-regular fa-floppy-disk"></i> Salva</button>
            </div>
            <div class="col-md-1 d-flex justify-content-center">
                <button type="button" class="btn btn-warning btn-lg"><a style="text-decoration: none;" asp-controller="ImgForCarousel" asp-action="Index" asp-route-id="@Model.ImageId"><i class="fas far fa-rotate-left"></i>Annulla</a></button>
            </div>
        </div>
        <div class="row">
            <div class="col-12" asp-validation-summary="All"></div>
        </div>
        <input type="hidden" asp-for="ImageId">
        <input type="hidden" asp-for="ImageEventCreator" value="me medesimo modiica">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ImageContentTitle"></label>
                    <input type="text" class="form-control form-control-lg" asp-for="ImageContentTitle">
                    <span asp-validation-for="ImageContentTitle"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageLabel"></label>
                    <input type="text" class="form-control" asp-for="ImageLabel">
                    <span asp-validation-for="ImageLabel"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageContentDescription"></label>
                    <textarea data-summernote rows="10" class="form-control"  asp-for="ImageContentDescription"></textarea>
                    <span asp-validation-for="ImageContentDescription"></span>
                </div>
                <div class="form-group">
                    @{
                        if (!string.IsNullOrEmpty(Model.ImagePath))
                        {
                            <label asp-for="ImagePath"></label>
                            <div class="preview-container">
                                <img id="previewImage" src="\@Model.ImagePath" asp-append-version="true"/>
                            </div>
                        }
                    }
                    <div class="custom-file pt-3">
                        <label class="custom-file-label" asp-for="Image"></label>
                        <input type="file" id="uploadInput" class="custom-file-input" asp-for="Image" onchange="handleImageUpload(event)">
                        <p><small>L'immagine verrá ridimensionata per adeguarla al sito.</small></p>
                        <span asp-validation-for="Image"></span>
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>
@section Scripts{
    <partial name="_Summernote"></partial>
    <partial name="_Validation"></partial>
    <script>
        function handleImageUpload(event) {
            const input = event.target;
            if (input.files && input.files[0]) {
                const reader = new FileReader();

                reader.onload = function (e) {
                    const img = new Image();
                    img.src = e.target.result;

                    img.onload = function () {
                        const canvas = document.createElement('canvas');
                        const ctx = canvas.getContext('2d');

                        // Imposta le dimensioni desiderate per l'anteprima
                        const maxWidth = 546;
                        const maxHeight = 410;

                        let newWidth = img.width;
                        let newHeight = img.height;

                        // Ridimensiona l'immagine se supera le dimensioni massime
                        if (img.width > maxWidth || img.height > maxHeight) {
                            const aspectRatio = img.width / img.height;
                            if (aspectRatio > 1) {
                                newWidth = maxWidth;
                                newHeight = maxWidth / aspectRatio;
                            } else {
                                 newHeight = maxHeight;
                                newWidth = maxHeight * aspectRatio;
                            }
                        }

                        canvas.width = newWidth;
                        canvas.height = newHeight;

                        ctx.drawImage(img, 0, 0, newWidth, newHeight);

                        // Mostra l'anteprima nell'elemento immagine
                        const previewImage = document.getElementById('previewImage');
                         previewImage.src = canvas.toDataURL('image/jpeg');
                    };
                };
                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>
}

Views/Home/Index.cshtml
@model dynamic
@{
    var santoDiOggi =string.Concat("Oggi ", DateTime.Now.ToString("dddd, dd MMMM yyyy"), " la Chiesa ricorda ");
}

<div class="text-center">
    @if (DateTime.Now.Hour<12)
    {
        <p><H5 class="textRotate">Buongiorno. @santoDiOggi <span class="rotate">@Model.santiDelGiorno</span></H5></p>
    }
    else if (DateTime.Now.Hour<17)
    {
        <p><H5 class="textRotate">Buon Pomeriggio. @santoDiOggi <span class="rotate">@Model.santiDelGiorno</span></h5></p> 
    }else{
        <p><H5 class="textRotate">Buonasera. @santoDiOggi <span class="rotate">@Model.santiDelGiorno</span></H5></p>
    }
</div>
<section>
    <div class="row">
        <div class="col-md-1">
            &nbsp; <!-- TODO: andra' messo il pulsante elimina -->
        </div>
        <div class="col-md-5">
            <div class="row p-2">
                <div style="color:#466db8;" class="col-md-12  d-flex justify-content-center"> 
                    <h5><b>INIZIATIVE IN CORSO</b></h5>&nbsp;
                </div>
            </div>
            <div class="d-flex justify-content-center customShadow">
                <div id="carouselExampleDark" class="carousel carousel-dark slide w-100">
                    <div class="carousel-indicators">
                        @{
                            int i = 0;                  
                            foreach (ImgForCarouselViewModel imgForCarouselViewModel in Model.imgForCarousel) 
                            {
                                <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="@i" @(i == 0 ? "class=active" : "") @(i == 0 ? "aria-current=true" : "") aria-label="@imgForCarouselViewModel.ImageLabel"></button>
                                i++;
                            };
                        }         
                    </div>
                    <div class="carousel-inner">
                    @{
                        
                        i = 0;
                        foreach (ImgForCarouselViewModel imgForCarouselViewModel in Model.imgForCarousel)
                        {                       
                            if (i == 0)
                            {
                                <div class="carousel-item active" data-bs-interval="10000">
                                    <img src="@imgForCarouselViewModel.ImagePath" class="d-block w-100" alt="@imgForCarouselViewModel.ImageLabel" asp-append-version="true">
                                    <div class="carousel-caption d-none d-md-block">
                                        <h5>@imgForCarouselViewModel.ImageLabel</h5>
                                        <p>
                                            <a asp-area="" asp-controller="ImgForCarousel" asp-action="Index" asp-route-id="@imgForCarouselViewModel.ImageId">@imgForCarouselViewModel.ImageContentTitle</a>
                                        </p>
                                    </div>
                                </div>
                            }else{                             
                                <div class="carousel-item" data-bs-interval="3000">
                                    <img src="@imgForCarouselViewModel.ImagePath" class="d-block w-100" alt="@imgForCarouselViewModel.ImageLabel" asp-append-version="true">
                                    <div class="carousel-caption d-none d-md-block">
                                        <h5>@imgForCarouselViewModel.ImageLabel</h5>
                                        <p>
                                            <a asp-area="" asp-controller="ImgForCarousel" asp-action="Index" asp-route-id="@imgForCarouselViewModel.ImageId">@imgForCarouselViewModel.ImageContentTitle</a>
                                        </p>
                                    </div>
                                </div>
                            }                             
                            i++;
                        };
                    }
                    </div>            
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
            <div class="row p-2">
                <div class="col-md-12 container d-flex justify-content-center">
                    <a class="btn btn-outline-primary btn-sm" asp-action="CreateInitiative"><i class="fas fa-plus"></i> Crea nuova</a>
                </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="d-flex justify-content-center customShadow">
                <aside>
                    <img src="@Model.appuntamentiDellaSettimana.PathFoto" class="d-block w-100" alt="Appuntamenti della settimana" asp-append-version="true" />
                </aside>
            </div>
            <div class="row p-2">
                <div class="d-flex justify-content-center">
                    <a class="btn btn-outline-primary btn-sm mr-5" asp-controller="Home" asp-action="EditAppuntamentiDellaSettimana" asp-route-id="@Model.appuntamentiDellaSettimana.IdFoto"><i class="fas fa-pencil-alt"></i> Modifica</a>
                </div>  
            </div>
          </div>
      </div>
</section>